import os
import struct
import numpy as np
from typing import Dict, List, Tuple, Union, Optional
import time


def load_string_to_string_map(path: str) -> Dict[str, str]:
    """
    Load a binary file containing a string-to-string map.
    
    Args:
        path: Path to the binary file
        
    Returns:
        Dictionary mapping strings to strings
    """
    result = {}
    with open(path, "rb") as f:
        size, = struct.unpack("<I", f.read(4))
        for _ in range(size):
            key_len, = struct.unpack("<I", f.read(4))
            key = f.read(key_len).decode('utf-8')
            val_len, = struct.unpack("<I", f.read(4))
            val = f.read(val_len).decode('utf-8')
            result[key] = val
    return result

def load_string_to_uint_map(path: str) -> Dict[str, int]:
    """
    Load a binary file containing a string-to-uint32 map.
    
    Args:
        path: Path to the binary file
        
    Returns:
        Dictionary mapping strings to integers
    """
    result = {}
    with open(path, "rb") as f:
        size, = struct.unpack("<I", f.read(4))
        for _ in range(size):
            strlen, = struct.unpack("<I", f.read(4))
            key = f.read(strlen).decode('utf-8')
            val, = struct.unpack("<I", f.read(4))
            result[key] = val
    return result

def load_uint_to_string_map(path: str) -> Dict[int, str]:
    """
    Load a binary file containing a uint32-to-string map.
    
    Args:
        path: Path to the binary file
        
    Returns:
        Dictionary mapping integers to strings
    """
    result = {}
    with open(path, "rb") as f:
        size, = struct.unpack("<I", f.read(4))
        for _ in range(size):
            key, = struct.unpack("<I", f.read(4))
            strlen, = struct.unpack("<I", f.read(4))
            value = f.read(strlen).decode('utf-8')
            result[key] = value
    return result

def load_uint32_binary(path: str) -> np.ndarray:
    """
    Load a binary file containing an array of uint32 values.
    
    Args:
        path: Path to the binary file
        
    Returns:
        NumPy array of uint32 values
    """
    
    
    return np.fromfile(path, dtype=np.uint32)

class KnowledgeBase:
    """
    Class to load and work with the Freebase graph data generated by process_freebase2.cpp
    """
    
    def __init__(self, data_dir: str = ""):
        """
        Initialize the graph by loading data from the specified directory.
        
        Args:
            data_dir: Directory containing the graph data files
        """
        
    
        current_file_path = os.path.abspath(__file__)
        last_slash_index = current_file_path.rfind('/')
        if last_slash_index != -1:
            current_directory = current_file_path[:last_slash_index]
        
        # Get the directory where the current file is located
        # current_directory = os.path.dirname(current_file_path)
        if data_dir:
            self.data_dir = data_dir
        else:
            self.data_dir = current_directory

        #self.data_dir = current_directory 
        print("Loading graph data from:", data_dir)
        # Load outgoing edges
        self.out_indptr = load_uint32_binary(os.path.join(self.data_dir, "graph_out_indptr.bin"))
        self.out_indices = load_uint32_binary(os.path.join(self.data_dir, "graph_out_indices.bin"))
        self.out_data = load_uint32_binary(os.path.join(self.data_dir, "graph_out_data.bin"))
        
        # Load incoming edges
        self.in_indptr = load_uint32_binary(os.path.join(self.data_dir, "graph_in_indptr.bin"))
        self.in_indices = load_uint32_binary(os.path.join(self.data_dir, "graph_in_indices.bin"))
        self.in_data = load_uint32_binary(os.path.join(self.data_dir, "graph_in_data.bin"))
        
        # Number of nodes in the graph
        self.num_nodes = len(self.out_indptr) - 1
        # Number of edges in the graph
        self.num_out_edges = len(self.out_indices)
        self.num_in_edges = len(self.in_indices)
        
        print(f"Graph loaded with {self.num_nodes} nodes, {self.num_out_edges} outgoing edges, and {self.num_in_edges} incoming edges")
        
        # Load entity and predicate mappings
        print("Loading entity and predicate mappings...")
        self.entity_to_id = load_string_to_uint_map(os.path.join(self.data_dir, "vertex_label_to_id.bin"))
        self.id_to_entity = load_uint_to_string_map(os.path.join(self.data_dir, "vertex_id_to_label.bin"))
        self.predicate_to_id = load_string_to_uint_map(os.path.join(self.data_dir, "edge_label_to_id.bin"))
        self.id_to_predicate = load_uint_to_string_map(os.path.join(self.data_dir, "edge_id_to_label.bin"))
        
        # Load human readable names (if available)
        entity_to_name_path = os.path.join(self.data_dir, "entity_to_name.bin")
        if os.path.exists(entity_to_name_path):
            print("Loading human readable entity names...")
            self.entity_to_name = load_string_to_string_map(entity_to_name_path)
        else:
            self.entity_to_name = {}
            
        print(f"Loaded {len(self.entity_to_id)} entities and {len(self.predicate_to_id)} predicates")
        
    def get_edge_num(self, node_id: str) -> int:
        
        node_id  = self.entity_to_id[node_id]
        # Convert to 0-based indexing for internal use
        node_idx = node_id - 1
        
        if node_idx < 0 or node_idx >= self.num_nodes:
            return []
        
        start_idx_out = self.out_indptr[node_idx]
        end_idx_out = self.out_indptr[node_idx + 1]

        start_idx_in = self.in_indptr[node_idx]
        end_idx_in = self.in_indptr[node_idx + 1]
        # Get neighbors and edge labels, convert neighbor indices back to 1-based
        return (end_idx_out - start_idx_out) + (end_idx_in - start_idx_in)

    def get_out_neighbors(self, node_id: int) -> List[Tuple[int, int]]:
        """
        Get the outgoing neighbors of a node and the edge labels.
        
        Args:
            node_id: 1-based node ID (as used in the CPP code)
            
        Returns:
            List of (neighbor_id, edge_label_id) tuples
            Note: neighbor_id is 1-based to match the original CPP indexing
        """
        # Convert to 0-based indexing for internal use
        node_idx = node_id - 1
        
        if node_idx < 0 or node_idx >= self.num_nodes:
            return []
        
        start_idx = self.out_indptr[node_idx]
        end_idx = self.out_indptr[node_idx + 1]
        
        # Get neighbors and edge labels, convert neighbor indices back to 1-based
        return [(int(self.out_indices[i]) + 1, int(self.out_data[i])) for i in range(start_idx, end_idx)]
    


    def get_in_neighbors(self, node_id: int) -> List[Tuple[int, int]]:
        """
        Get the incoming neighbors of a node and the edge labels.
        
        Args:
            node_id: 1-based node ID (as used in the CPP code)
            
        Returns:
            List of (neighbor_id, edge_label_id) tuples
            Note: neighbor_id is 1-based to match the original CPP indexing
        """
        # Convert to 0-based indexing for internal use
        node_idx = node_id - 1
        
        if node_idx < 0 or node_idx >= self.num_nodes:
            return []
        
        start_idx = self.in_indptr[node_idx]
        end_idx = self.in_indptr[node_idx + 1]
        
        # Get neighbors and edge labels, convert neighbor indices back to 1-based
        return [(int(self.in_indices[i]) + 1, int(self.in_data[i])) for i in range(start_idx, end_idx)]
    
    def get_neighbors(self, node_id: int) -> List[Tuple[int, int, bool]]:
        """
        Get both incoming and outgoing neighbors of a node and the edge labels.
        
        Args:
            node_id: 1-based node ID (as used in the CPP code)
            
        Returns:
            List of (neighbor_id, edge_label_id, is_outgoing) tuples
            Note: neighbor_id is 1-based to match the original CPP indexing
            Note: is_outgoing is True for outgoing edges, False for incoming edges
        """
        out_neighbors = [(neighbor, edge, True) for neighbor, edge in self.get_out_neighbors(node_id)]
        in_neighbors = [(neighbor, edge, False) for neighbor, edge in self.get_in_neighbors(node_id)]
        
        return out_neighbors + in_neighbors
    

    
    def lookup_entity(self, entity_str: str) -> Optional[int]:
        """
        Look up an entity ID by its string representation.
        
        Args:
            entity_str: Entity string
            
        Returns:
            Entity ID (1-based) or None if not found
        """
        return self.entity_to_id.get(entity_str)
    
    def lookup_predicate(self, predicate_str: str) -> Optional[int]:
        """
        Look up a predicate ID by its string representation.
        
        Args:
            predicate_str: Predicate string
            
        Returns:
            Predicate ID or None if not found
        """
        return self.predicate_to_id.get(predicate_str)

    def get_predicate_name(self, predicate_id: int) -> str:
        """
        Get the string representation of a predicate.
        
        Args:
            predicate_id: Predicate ID
            
        Returns:
            Predicate string or "Unknown predicate" if not found
        """
        if predicate_id in self.id_to_predicate:
            return self.id_to_predicate[predicate_id]
        return f"Unknown predicate {predicate_id}"

    def get_entity_name(self, entity_str):
        """Get the human-readable name for an entity given its m.xxx or g.xxx identifier"""
        if entity_str == None:
            raise ValueError("entity_str is None")
        if not (entity_str.startswith("m.") or entity_str.startswith("g.") ):# time and specific numbers
            return entity_str
        
        if entity_str in self.entity_to_name:
            return self.entity_to_name[entity_str]
        else:
            return "UnName_Entity" # If not found, return the original content
    def _should_abandon_relation(self, relation):
        """Determine whether to filter out a certain relation"""
        if relation == "common.topic.image":
            return False
        if relation =="common.topic.notable_types":
            return False
        return (relation == "type.object.type" or 
                relation == "type.object.name" or 
                relation.startswith("common.")  or 
                relation.startswith("freebase.") or 
                "sameAs" in relation)

    def GetEdgeLabel(self, entity_str: str) -> list[dict]:
        """Get all relations of an entity (both head and tail entity relations)
           Input is the entity's m.xxxx identifier
        """
        # Get the numeric ID of the entity
        if not entity_str:
            raise ValueError("entity_str is None")
        if not (entity_str.startswith("m.") or entity_str.startswith("g.") ):# time and specific numbers
            return []
        entity_id = self.lookup_entity(entity_str)# look up ID
        
        if entity_id == None:
            return []
        else:
            neighbors = self.get_neighbors(entity_id)
            neighbors_edge_labels = [neighbor[1] for neighbor in neighbors]
            relation_label_set = set()
            neighbors_edge_labels_lst = []
            for edge_label in neighbors_edge_labels:
                relation_label = self.get_predicate_name(edge_label)
                if not self._should_abandon_relation(relation_label) and relation_label not in relation_label_set:
                    relation_label_set.add(relation_label)
                    neighbors_edge_labels_lst.append({"relation":relation_label,"is_head":None})
            return neighbors_edge_labels_lst
    
    
    def GetInVertex(self, entity_str: str, edge: str) -> list[tuple[str, str, str]]:
        """
        Get all vertices pointing to the specified entity, returned as triples
        
        Args:
            entity_str (str): Query entity ID in m.xxxx, date, or number format
            edge (str): feasible edge label
        
        Returns:
            list[tuple[str, str, str]]: List of triples, each element is (source_entity_id, relation, entity_id)
        """
        if not entity_str:
            raise ValueError("entity_str is None")
        
        results = []
        entity_id = self.lookup_entity(entity_str)
        if entity_id == None:
            return []
        else:
            in_neighbors = self.get_in_neighbors(entity_id)
            for neighbor in in_neighbors:
                neighbor_entity_id = neighbor[0]
                neighbor_entity_str = self.id_to_entity.get(neighbor_entity_id, None)
                neighbor_edge_label = neighbor[1]
                neighbor_edge_label_name = self.get_predicate_name(neighbor_edge_label)
                if neighbor_edge_label_name == edge:
                    results.append((neighbor_entity_str, neighbor_edge_label_name, entity_str))
            
            return list(set(results))

    def GetInVertexbyEdgeSet(self, entity_str: str, edge: set[str]) -> list[tuple[str, str, str]]:
        if not entity_str:
            raise ValueError("entity_str is None")
        
        results = []
        entity_id = self.lookup_entity(entity_str)
        if entity_id == None:
            return []
        else:
            in_neighbors = self.get_in_neighbors(entity_id)
            for neighbor in in_neighbors:
                neighbor_entity_id = neighbor[0]
                neighbor_entity_str = self.id_to_entity.get(neighbor_entity_id, None)
                neighbor_edge_label = neighbor[1]
                neighbor_edge_label_name = self.get_predicate_name(neighbor_edge_label)
                if neighbor_edge_label_name in edge:
                    results.append((neighbor_entity_str, neighbor_edge_label_name, entity_str))
            
            return list(set(results))
    
    def GetOutVertex(self, entity_str: str, edge: str) -> list[tuple[str, str, str]]:
        """
        Get all vertices starting from the specified entity, returned as triples
        
        Args:
            entity_str (str): Query entity ID in m.xxxx, date, or number format
            edge (str): feasible edge label
        
        Returns:
            list[tuple[str, str, str]]: List of triples, each element is (entity_id, relation, target_entity_id)
        """
        if not entity_str:
            raise ValueError("entity_str is None")
        
        results = []
        entity_id = self.lookup_entity(entity_str)
        if entity_id == None:
            return []
        else:
            out_neighbors = self.get_out_neighbors(entity_id)
            for neighbor in out_neighbors:
                neighbor_entity_id = neighbor[0]
                neighbor_entity_str = self.id_to_entity.get(neighbor_entity_id, None)
                neighbor_edge_label = neighbor[1]
                neighbor_edge_label_name = self.get_predicate_name(neighbor_edge_label)
                if neighbor_edge_label_name == edge:
                    results.append((entity_str, neighbor_edge_label_name, neighbor_entity_str))
            
            return list(set(results))

    def GetOutVertexbyEdgeSet(self, entity_str: str, edge: set[str]) -> list[tuple[str, str, str]]:
        if not entity_str:
            raise ValueError("entity_str is None")
        
        results = []
        entity_id = self.lookup_entity(entity_str)
        if entity_id == None:
            return []
        else:
            out_neighbors = self.get_out_neighbors(entity_id)
            for neighbor in out_neighbors:
                neighbor_entity_id = neighbor[0]
                neighbor_entity_str = self.id_to_entity.get(neighbor_entity_id, None)
                neighbor_edge_label = neighbor[1]
                neighbor_edge_label_name = self.get_predicate_name(neighbor_edge_label)
                if neighbor_edge_label_name in edge:
                    results.append((entity_str, neighbor_edge_label_name, neighbor_entity_str))
            
            return list(set(results))

    def GetVertex(self, entity_str: str, edge: str) -> list[tuple[str, str, str]]:
        """
        Get all vertices connected to the specified entity, returned as triples
        
        Args:
            entity_str (str): Query entity ID in m.xxxx, date, or number format
            edge (str): feasible edge label
        
        Returns:
            list[tuple[str, str, str]]: List of triples, each element is (entity_id, relation, connected_id)
        """
        if not entity_str:
            raise ValueError("entity_str is None")
        
        results = []
        entity_id = self.lookup_entity(entity_str)
        if entity_id == None:
            return []
        else:
            neighbors = self.get_neighbors(entity_id)
            for neighbor in neighbors:
                neighbor_entity_id = neighbor[0]
                neighbor_entity_str = self.id_to_entity.get(neighbor_entity_id, None)
                neighbor_edge_label = neighbor[1]
                neighbor_edge_label_name = self.get_predicate_name(neighbor_edge_label)
                if neighbor_edge_label_name == edge:
                    results.append((entity_str, neighbor_edge_label_name, neighbor_entity_str))
            
            return list(set(results))

    def GetVertexbyEdgeSet(self, entity_str: str, edge: set[str]) -> list[tuple[str, str, str]]:
        if not entity_str:
            raise ValueError("entity_str is None")
        
        results = []
        entity_id = self.lookup_entity(entity_str)
        if entity_id == None:
            return []
        else:
            neighbors = self.get_neighbors(entity_id)
            for neighbor in neighbors:
                neighbor_entity_id = neighbor[0]
                neighbor_entity_str = self.id_to_entity.get(neighbor_entity_id, None)
                neighbor_edge_label = neighbor[1]
                neighbor_edge_label_name = self.get_predicate_name(neighbor_edge_label)
                if neighbor_edge_label_name in edge:
                    results.append((entity_str, neighbor_edge_label_name, neighbor_entity_str))
            
            return list(set(results))

    def GetVertex_two_hop_search(self, entity_id: str, relation1: str ,relation2: str) -> list[tuple[str, str, str]]:
        """
        Two-hop bidirectional search
        
        Args:
            entity_id: Starting entity ID
            relation1: Relation used in the first hop
            relation2: Relation used in the second hop
        
        Returns:
            list[tuple[str, str, str]]: Returns two lists containing results from the first and second hops
            First hop return format: [(mid_entity_id, is_forward)]
            Second hop return format: [(mid_entity_id, final_entity_id, is_forward)]
        """
        second_hop = []
        one_hop_triples = self.GetVertex(entity_id,[relation1])
        for one_hop_triple in one_hop_triples:
            two_hop_triples = self.GetVertex(one_hop_triple[2],[relation2])
            for head2,relation_2,tail2 in two_hop_triples:
                second_hop.append((head2,relation_2,tail2,None))
        return None,list(set(second_hop))
    def GetVertex_three_hop_search(self, entity_id: str, relation1: str ,relation2: str, relation3: str) -> list[tuple[str, str, str]]:
        """
        Three-hop bidirectional search
        
        Args:
            entity_id: Starting entity ID
            relation1: Relation used in the first hop
            relation2: Relation used in the second hop
            relation3: Relation used in the third hop
        
        Returns:
            list[tuple[str, str, str]]: Returns two lists containing results from the first and second hops
            First hop return format: [(mid_entity_id, is_forward)]
            Second hop return format: [(mid_entity_id, final_entity_id, is_forward)]
        """
        three_hop = []
        one_hop_triples = self.GetVertex(entity_id,[relation1])
        for one_hop_triple in one_hop_triples:
            two_hop_triples = self.GetVertex(one_hop_triple[2],[relation2])
            for two_hop_triple in two_hop_triples:
                three_hop_triples = self.GetVertex(two_hop_triple[2],[relation3])
                for three_hop_triple in three_hop_triples:
                    three_hop.append((one_hop_triple[0],one_hop_triple[1],one_hop_triple[2],two_hop_triple[0],two_hop_triple[1],two_hop_triple[2],three_hop_triple[0],three_hop_triple[1],three_hop_triple[2]))
        return list(set(three_hop))

# Example usage
if __name__ == "__main__":
    # Load the graph from the default directory
    start_time = time.time()
    current_file = os.path.abspath(__file__)
    current_dir = os.path.dirname(current_file)# relative path
    freebase_dir = os.path.join(current_dir, "../../data/freebase/")
    graph = KnowledgeBase(freebase_dir)
    end_time = time.time()
    print(f"Loading time: {end_time - start_time}")
   # Show some stats
    print("\nGraph Statistics:")
    print(f"Number of nodes: {graph.num_nodes}")
    print(f"Number of out edges: {graph.num_out_edges}")
    print(f"Number of in edges: {graph.num_in_edges}")
    print(f"Number of predicates: {len(graph.predicate_to_id)}")
    
    # Get a sample entity
    if graph.num_nodes > 0:
        sample_id = 1  # First entity
        sample_entity = graph.id_to_entity.get(sample_id, "Unknown")
        sample_name = graph.get_entity_name(sample_entity)
        
        print(f"\nSample entity (ID={sample_id}):")
        print(f"  Entity string: {sample_entity}")
        print(f"  Human readable name: {sample_name}")
        
        # Get neighbors
        neighbors = graph.get_neighbors(sample_id)
        print(f"\nNeighbors of entity {sample_id} ({sample_name}):")
        for i, (neighbor_id, edge_label,_) in enumerate(neighbors[:5]):  # Show first 5 neighbors
            neighbor_str = graph.id_to_entity.get(neighbor_id, "Unknown")
            neighbor_name = graph.get_entity_name(neighbor_str)
            edge_name = graph.get_predicate_name(edge_label)
            print(f"  {i+1}. {neighbor_name} via {edge_name}")
            
        if len(neighbors) > 5:
            print(f"  ... and {len(neighbors) - 5} more neighbors")  
        
